//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaRide.Application.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_az {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_az() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaRide.Application.Localize.Resource.az", typeof(Resource_az).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; artıq mövcuddur..
        /// </summary>
        public static string Exception_AlreadyExists {
            get {
                return ResourceManager.GetString("Exception.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; üçün giriş məlumatları səhvdir..
        /// </summary>
        public static string Exception_InvalidCredentials {
            get {
                return ResourceManager.GetString("Exception.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; tapılmadı.
        /// </summary>
        public static string Exception_NotFound {
            get {
                return ResourceManager.GetString("Exception.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; nömrə artıq təsdiqlənib. .
        /// </summary>
        public static string Exception_PhoneConfirmed {
            get {
                return ResourceManager.GetString("Exception.PhoneConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; nömrəsi ilə qeydiyyatlı heç bir istifadəçi tapılmadı..
        /// </summary>
        public static string Exception_PhoneNotFound {
            get {
                return ResourceManager.GetString("Exception.PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; nömrə artıq istifadə olunur..
        /// </summary>
        public static string Exception_PhoneTaken {
            get {
                return ResourceManager.GetString("Exception.PhoneTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; identifikasiyalı qadağa tapılmadı.
        /// </summary>
        public static string Exception_RestrictionNotFound {
            get {
                return ResourceManager.GetString("Exception.RestrictionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; identifikasiyalı səyahət tapılmadı..
        /// </summary>
        public static string Exception_RideNotFound {
            get {
                return ResourceManager.GetString("Exception.RideNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə çox bəsitdir.
        /// </summary>
        public static string Validation_Password {
            get {
                return ResourceManager.GetString("Validation.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon formadı düzgün deyil..
        /// </summary>
        public static string Validation_Phone {
            get {
                return ResourceManager.GetString("Validation.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; xanası yalnız {1} - {2} arasında ola bilər..
        /// </summary>
        public static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation.Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; xanası boş ola bilməz..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu istifadəçinin bu əməliyyatı etmək üçün səlahiyyəti yoxdur..
        /// </summary>
        public static string Validation_UserHasNotAccessToOperation {
            get {
                return ResourceManager.GetString("Validation.UserHasNotAccessToOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin ShaRide kodunuz : {0}.
        /// </summary>
        public static string VerificationSms_Confirmation {
            get {
                return ResourceManager.GetString("VerificationSms.Confirmation", resourceCulture);
            }
        }
    }
}
